import { defineConfig, type Plugin } from 'vite'
import path from 'path'
import fs from 'fs'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

function presentationRegistryPlugin(): Plugin {
  const registryPath = path.resolve(__dirname, 'src/registry.ts')
  const presentationsDir = path.resolve(__dirname, 'presentations')

  function scanPresentations(): object[] {
    if (!fs.existsSync(presentationsDir)) return []

    return fs
      .readdirSync(presentationsDir, { withFileTypes: true })
      .filter((entry) => entry.isDirectory() && !entry.name.startsWith('_'))
      .map((entry) => {
        const manifestPath = path.join(presentationsDir, entry.name, 'presentation.json')
        if (!fs.existsSync(manifestPath)) return null
        try {
          return JSON.parse(fs.readFileSync(manifestPath, 'utf-8'))
        } catch {
          console.warn(`[registry] Failed to parse ${manifestPath}`)
          return null
        }
      })
      .filter((p): p is object => p !== null)
      .sort((a, b) => {
        const aDate = (a as Record<string, string>)['date']
        const bDate = (b as Record<string, string>)['date']
        const aTitle = (a as Record<string, string>)['title'] ?? ''
        const bTitle = (b as Record<string, string>)['title'] ?? ''
        if (aDate && bDate) return bDate.localeCompare(aDate)
        if (aDate) return -1
        if (bDate) return 1
        return aTitle.localeCompare(bTitle)
      })
  }

  function generateRegistry() {
    const presentations = scanPresentations()

    const code = `// AUTO-GENERATED — do not edit manually
// Regenerated by vite on build start and when presentation.json files change

import type { PresentationMeta } from './types'

export const presentations: PresentationMeta[] = ${JSON.stringify(presentations, null, 2)}
`
    fs.mkdirSync(path.dirname(registryPath), { recursive: true })
    fs.writeFileSync(registryPath, code, 'utf-8')
    console.log(`[registry] ${presentations.length} presentation(s)`)
  }

  return {
    name: 'presentation-registry',
    buildStart() {
      generateRegistry()
    },
    closeBundle() {
      // Copy presentations/ verbatim into dist/ — Vite only outputs registered
      // entry points, so slide HTML files must be copied explicitly.
      const outDir = path.resolve(__dirname, 'dist/presentations')
      if (fs.existsSync(presentationsDir)) {
        fs.cpSync(presentationsDir, outDir, { recursive: true })
        console.log('[registry] Copied presentations/ → dist/presentations/')
      }

      // Copy themes/ verbatim into dist/ — referenced by slide HTML files
      // via relative paths (../../themes/<theme>.css).
      const themesDir = path.resolve(__dirname, 'themes')
      const themesOutDir = path.resolve(__dirname, 'dist/themes')
      if (fs.existsSync(themesDir)) {
        fs.cpSync(themesDir, themesOutDir, { recursive: true })
        console.log('[registry] Copied themes/ → dist/themes/')
      }
    },
    configureServer(server) {
      server.watcher.add(presentationsDir)
      server.watcher.on('change', (file) => {
        if (file.includes('presentation.json')) {
          generateRegistry()
          const mod = server.moduleGraph.getModuleById(registryPath)
          if (mod) server.moduleGraph.invalidateModule(mod)
          server.hot.send({ type: 'full-reload' })
        }
      })
      server.watcher.on('addDir', (dir) => {
        if (dir.startsWith(presentationsDir)) {
          generateRegistry()
          server.hot.send({ type: 'full-reload' })
        }
      })
    },
  }
}

export default defineConfig({
  // Set to '/' when using a custom domain.
  base: '/gridcom-slides/',
  build: {
    rollupOptions: {
      input: {
        main: path.resolve(__dirname, 'index.html'),
        viewer: path.resolve(__dirname, 'viewer.html'),
      },
    },
  },
  plugins: [presentationRegistryPlugin()],
  server: {
    fs: {
      allow: ['.'],
    },
  },
})
